name = "Unicorn"
uuid = "46d714ca-0d86-11eb-00be-15840351e17c"
authors = ["lucca <lucca.fraser@gmail.com>"]
version = "0.1.0"

[deps]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
BitFlags = "d1d4a3ce-64b1-5f1a-9ba4-7e7e69966f35"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
unicorn_jll = "213bd155-00d0-5096-9019-d950e7998be8"
